### ISSUE TITLE
how to play it？ maybe im so stupid

### ISSUE THREAD

**Issue by tcyh1221** [jiaweit2/BallGame#1]

**Comment by jiaweit2** [comment]
Iol It's totally my bad not giving enough description, since it is an incomplete project. It has been a while since I made the game but if you get a chance to make it run in WeChat, here are the rules.

Rule1: Touch the screen to start the game. The objective is to keep the ball moving forward.
Rule2: Press and hold on the screen and release to make the ball jump. Longer you hold, higher it can jump.
Rule3: If the block ahead is not in place(where you can see its shadow), you need to slide left to make ball "be" in its own shadow so that in the "shadow world", the ball can keep moving forward. You may slide right to make ball be in the "real world" again. There are times that you need to slide into the "shadow world" or you need to slide back to the "real world".

Thanks for trying it. Hope you have some fun at least.

**Comment by tcyh1221** [comment]
Thank you very much for your reply.Im just a noob for wechat game.Im trying again now.lol
